### ISSUE TITLE
Error message !!!

### ISSUE THREAD

**Issue by wermaxta** [entropy1337/infernal-twin#1]
OS Kali Linux 

root@kali:~/infernal-twin# python evil_twin.py
WARNING: No route found for IPv6 destination :: (no default route?)
********************
********************
Evil Twin Attack Reburn
********************
Setting up the database

Database and appropriate file is created
Creating a DB file
Enter the username of the DB: test
Enter the password of the DB: test
Traceback (most recent call last):
  File "evil_twin.py", line 10, in <module>
    import create_db_hotspot
  File "/root/infernal-twin/create_db_hotspot.py", line 44, in <module>
    connect_to_database()
  File "/root/infernal-twin/create_db_hotspot.py", line 11, in connect_to_database
    db_connection = MySQLdb.connect(host='localhost', user=dbusername, passwd=dbpassword)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
root@kali:~/infernal-twin#

**Comment by entropy1337** [comment]
Thanks for the info. 
I have modified the script and changed the code a bit. it should work now
